### ISSUE TITLE
requests for datasets

### ISSUE THREAD

**Issue by kitezh0307** [bhsimon0810/text-classification#1]
Hello,the link for datasets is broken，if it's convenient for you,could you send me the datasets.Thank you very much!

**Comment by yphua** [comment]
The link to the dataset is not invalid, it is that I do not have permission to access it

**Comment by bhsimon0810** [comment]
Sorry for not checking the issue these days. If you still need the data, there is a [share link](https://pan.baidu.com/s/1WWq0Tquju2BhYtFEX_FLgw) with password `yxmi`.
